use Group85;
set SQL_SAFE_UPDATES = 0;
update users set ofstate = 'AL' where ofstate = 'Alabama';
update users set ofstate = 'AK' where ofstate = 'Alaska';
update users set ofstate = 'AZ' where ofstate = 'Arizona';
update users set ofstate = 'AR' where ofstate = 'Arkansas';
update users set ofstate = 'CA' where ofstate = 'California';
update users set ofstate = 'CO' where ofstate = 'Colorado';
update users set ofstate = 'CT' where ofstate = 'Connecticut';
update users set ofstate = 'DE' where ofstate = 'Delaware';
update users set ofstate = 'FL' where ofstate = 'Florida';
update users set ofstate = 'GA' where ofstate = 'Georgia';
update users set ofstate = 'HI' where ofstate = 'Hawaii';
update users set ofstate = 'ID' where ofstate = 'Idaho';
update users set ofstate = 'IL' where ofstate = 'Illinois';
update users set ofstate = 'IN' where ofstate = 'Indiana';
update users set ofstate = 'IA' where ofstate = 'Iowa';
update users set ofstate = 'KS' where ofstate =  'Kansas';
update users set ofstate = 'KY' where ofstate = 'Kentucky';
update users set ofstate = 'LA' where ofstate = 'Louisiana';
update users set ofstate = 'ME' where ofstate = 'Maine';
update users set ofstate = 'MD' where ofstate = 'Maryland';
update users set ofstate = 'MA' where ofstate = 'Massachusetts';
update users set ofstate = 'MI' where ofstate = 'Michigan';
update users set ofstate = 'MN' where ofstate = 'Minnesota';
update users set ofstate = 'MS' where ofstate = 'Mississippi';
update users set ofstate = 'MO' where ofstate = 'Missouri';
update users set ofstate = 'MT' where ofstate ='Montana';
update users set ofstate ='NE' where ofstate ='Nebraska';
update users set ofstate = 'NV' where ofstate ='Nevada';
update users set ofstate = 'NH' where ofstate ='New Hampshire' ;
update users set ofstate = 'NJ' where ofstate ='New Jersey' ;
update users set ofstate = 'NM' where ofstate ='New Mexico';
update users set ofstate = 'NY' where ofstate ='New York' ;
update users set ofstate = 'NC' where ofstate ='North Carolina';
update users set ofstate = 'ND' where ofstate ='North Dakota';
update users set ofstate = 'OH' where ofstate ='Ohio' ;
update users set ofstate = 'OK' where ofstate ='Oklahoma' ;
update users set ofstate = 'OR' where ofstate ='Oregon' ;
update users set ofstate = 'PA' where ofstate ='Pennsylvania' ;
update users set ofstate = 'RI' where ofstate ='Rhode Island';
update users set ofstate = 'SC' where ofstate ='South Carolina' ;
update users set ofstate = 'SD' where ofstate ='South Dakota';
update users set ofstate = 'TN' where ofstate ='Tennessee';
update users set ofstate = 'TX' where ofstate ='Texas';
update users set ofstate = 'UT' where ofstate ='Utah' ;
update users set ofstate = 'VT' where ofstate ='Vermont';
update users set ofstate = 'VA' where ofstate ='Virginia' ;
update users set ofstate = 'WA' where ofstate ='Washington';
update users set ofstate = 'WV' where ofstate ='West Virginia';
update users set ofstate = 'MS' where ofstate ='Wisconsin';
update users set ofstate = 'WY' where ofstate ='Wyoming';